dataset_path = "io/dataset.bin"
start_iteration = 1
n_iterations = 10

[iteration]
n_plays = 1_000_000
concurrency = 50
output_dir = "io/models" # comment-out to skip saving
fee_per_contract_usd = 1.65 # NQ
multiplier = 20.0 # NQ
utility_penalty_bps = 0.01
max_play_duration_in_bars  = 900